name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Install dependencies using Poetry
      run: |
        poetry install

    - name: Build the package
      run: |
        poetry build
    - name: Debug Environment Variables
      run: |
        echo $env:POETRY_HTTP_BASIC_PYPI_USERNAME
        echo "Token length: $((echo $env:POETRY_HTTP_BASIC_PYPI_PASSWORD).Length)"
      shell: pwsh

    - name: Publish to PyPI
      env:
        POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry publish --build
